import type { SongDef } from '../score.ts';
import { afterglow } from './afterglow.ts';
import { blueDanube } from './blueDanube.ts';
import { canCan } from './canCan.ts';
import { caprice24 } from './caprice24.ts';
import { canon } from './canon.ts';
import { carolOfTheBells } from './carolOfTheBells.ts';
import { drunkenSailor } from './drunkenSailor.ts';
import { entertainer } from './entertainer.ts';
import { korobeiniki } from './korobeiniki.ts';
import { fifth } from './fifth.ts';
import { forty } from './forty.ts';
import { funeralMarch } from './funeralMarch.ts';
import { furElise } from './furElise.ts';
import { greensleeves } from './greensleeves.ts';
import { glassElevator } from './glassElevator.ts';
import { gymnopedie } from './gymnopedie.ts';
import { havaNagila } from './havaNagila.ts';
import { ignition } from './ignition.ts';
import { littleFugue } from './littleFugue.ts';
import { midnightDrive } from './midnightDrive.ts';
import { lowOrbit } from './lowOrbit.ts';
import { minuet } from './minuet.ts';
import { moonlight } from './moonlight.ts';
import { morningMood } from './morningMood.ts';
import { mountainKing } from './mountainKing.ts';
import { nachtmusik } from './nachtmusik.ts';
import { neonSkyline } from './neonSkyline.ts';
import { odeToJoy } from './odeToJoy.ts';
import { pompAndCircumstance } from './pompAndCircumstance.ts';
import { pocketChange } from './pocketChange.ts';
import { preludeInC } from './preludeInC.ts';
import { redline } from './redline.ts';
import { rustBelt } from './rustBelt.ts';
import { saints } from './saints.ts';
import { spring } from './spring.ts';
import { seventhGear } from './seventhGear.ts';
import { sundayTape } from './sundayTape.ts';
import { swanLake } from './swanLake.ts';
import { switchback } from './switchback.ts';
import { toccata } from './toccata.ts';
import { valkyries } from './valkyries.ts';
import { washerwoman } from './washerwoman.ts';
import { williamTell } from './williamTell.ts';
import { mars, mercury, jupiter } from './planets.ts';
import { paperHearts, cityLights, goldenHour } from './popSingles.ts';
import { warehouseCurrent, prismParade, assemblyLine, photonRun } from './robotSuite.ts';

/** The built-in songs, in the order they are listed. */
export const STARTER_SONGS: SongDef[] = [odeToJoy, ignition, midnightDrive, neonSkyline, furElise, canon, mountainKing, redline, fifth, nachtmusik, forty, toccata, preludeInC, minuet, williamTell, swanLake, valkyries, blueDanube, morningMood, moonlight, funeralMarch, entertainer, carolOfTheBells, korobeiniki, drunkenSailor, spring, littleFugue, pompAndCircumstance, canCan, greensleeves, washerwoman, havaNagila, saints, gymnopedie, caprice24, glassElevator, pocketChange, switchback, rustBelt, lowOrbit, seventhGear, afterglow, sundayTape, mars, mercury, jupiter, paperHearts, cityLights, goldenHour, warehouseCurrent, prismParade, assemblyLine, photonRun];
