/**
 * Level trims (dB) that bring the built-in songs to about the same loudness. Written by
 * `node tests/tools/loudness.ts --write`; songs not listed play at 0 dB.
 */
export const LEVELS: Record<string, number> = {
  'afterglow-protocol': -0.4,
  'assembly-line': 1.2,
  'blue-danube': -0.8,
  'can-can': 0,
  'canon': -2.2,
  'caprice-24': -2.1,
  'carol-of-the-bells': -3.4,
  'city-lights': 2.8,
  'drunken-sailor': -2.4,
  'entertainer': 0.8,
  'fifth': -2.4,
  'forty': -1.3,
  'funeral-march': -0.6,
  'fur-elise': -0.5,
  'glass-elevator': 0.2,
  'golden-hour': 0.3,
  'greensleeves': 2.1,
  'gymnopedie': -0.9,
  'hava-nagila': -1.7,
  'ignition': -2.7,
  'irish-washerwoman': -1.6,
  'jupiter-jollity': 2.7,
  'korobeiniki': -1.6,
  'little-fugue': 0.8,
  'low-orbit': -0.4,
  'mars-war-machine': 2.1,
  'mercury-winged-messenger': 2.3,
  'midnight-drive': -0.5,
  'minuet-in-g': 1.6,
  'moonlight': -1.5,
  'morning-mood': 1.1,
  'mountain-king': -2.5,
  'nachtmusik': -0.4,
  'neon-skyline': -1.9,
  'ode-to-joy': -4,
  'paper-hearts': 2.3,
  'photon-run': 2.7,
  'pocket-change': -1.7,
  'pomp-and-circumstance': 0.5,
  'prelude-c': 0,
  'prism-parade': 3,
  'redline': -3,
  'rust-belt-shuffle': -1.1,
  'seventh-gear': -2.7,
  'spring': -0.5,
  'sunday-tape': 2.9,
  'swan-lake': 0.2,
  'switchback': 0.8,
  'toccata': -2.4,
  'valkyries': -2.7,
  'warehouse-current': 1,
  'when-the-saints': 2.2,
  'william-tell': -3.5,
};
