/** Full-song EBU R128 trims. Reproduce with tests/tools/starter-audio-audit.mjs --write. */
export const LEVELS: Record<string, number> = {
  'afterglow-protocol': -5.1,
  'canon': -9.3,
  'caprice-24': -9.2,
  'carol-of-the-bells': -9.5,
  'drunken-sailor': -7.9,
  'glass-elevator': -6.9,
  'greensleeves': -7.2,
  'gymnopedie': -8.5,
  'ignition': -9.6,
  'irish-washerwoman': -9.2,
  'korobeiniki': -8.1,
  'low-orbit': -8.9,
  'midnight-drive': -5.7,
  'moonlight': -8.2,
  'mountain-king': -9.3,
  'neon-skyline': -6.6,
  'photon-run': -2,
  'pocket-change': -8.5,
  'rust-belt-shuffle': -7.6,
  'seventh-gear': -9.3,
  'sunday-tape': -3.2,
  'switchback': -7.9,
  'toccata': -9.7,
  'warehouse-current': -2.5,
};
